// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// csrng -- COMPILE-CHECK TESTBENCH   (generated by IP/scripts/gen_tb.py)
//
// A skeleton, not a verification environment. It proves the RTL and its
// dependencies elaborate and a UVM test can start and finish. Every input
// is tied to a constant; nothing is stimulated and nothing is checked.
// Building the environment is the exercise -- see ../README.md.

module tb;

  import uvm_pkg::*;
  import csrng_test_pkg::*;
  import csrng_pkg::*;
  import csrng_reg_pkg::*;
  `include "uvm_macros.svh"

  // Clocks. The main bus clock is 100 MHz to match Earl Grey; slow
  // domains (aon / core / usb) get their own so the ratio is realistic.
  logic clk, rst_n;

  initial begin
    clk = 1'b0;
    forever #5ns clk = ~clk;
  end

  initial begin
    rst_n = 1'b0;
    repeat (10) @(posedge clk);
    rst_n = 1'b1;
  end

  // Parameters the port widths depend on, copied from the module
  // header. The DUT is instantiated with defaults, so these match.
  localparam int unsigned NumHwApps = NumApps - 1;

  // Port declarations. Inputs are tied to constants -- never floating.
  tlul_pkg::tl_h2d_t tl_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t tl_o ;
  prim_mubi_pkg::mubi8_t otp_en_csrng_sw_app_read_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_hw_debug_en_i = '0;
  entropy_src_pkg::entropy_src_hw_if_req_t entropy_src_hw_if_o ;
  entropy_src_pkg::entropy_src_hw_if_rsp_t entropy_src_hw_if_i = '0;
  csrng_req_t [NumHwApps-1:0] csrng_cmd_i = '0;
  csrng_rsp_t [NumHwApps-1:0] csrng_cmd_o ;
  prim_alert_pkg::alert_rx_t [NumAlerts-1:0] alert_rx_i = '{default: prim_alert_pkg::ALERT_RX_DEFAULT};
  prim_alert_pkg::alert_tx_t [NumAlerts-1:0] alert_tx_o ;
  logic intr_cs_cmd_req_done_o ;
  logic intr_cs_entropy_req_o ;
  logic intr_cs_hw_inst_exc_o ;
  logic intr_cs_fatal_err_o ;

  csrng dut (
    .clk_i (clk),
    .rst_ni (rst_n),
    .tl_i (tl_i),
    .tl_o (tl_o),
    .otp_en_csrng_sw_app_read_i (otp_en_csrng_sw_app_read_i),
    .lc_hw_debug_en_i (lc_hw_debug_en_i),
    .entropy_src_hw_if_o (entropy_src_hw_if_o),
    .entropy_src_hw_if_i (entropy_src_hw_if_i),
    .csrng_cmd_i (csrng_cmd_i),
    .csrng_cmd_o (csrng_cmd_o),
    .alert_rx_i (alert_rx_i),
    .alert_tx_o (alert_tx_o),
    .intr_cs_cmd_req_done_o (intr_cs_cmd_req_done_o),
    .intr_cs_entropy_req_o (intr_cs_entropy_req_o),
    .intr_cs_hw_inst_exc_o (intr_cs_hw_inst_exc_o),
    .intr_cs_fatal_err_o (intr_cs_fatal_err_o)
  );

  tb_clk_if clk_if (.clk(clk), .rst_n(rst_n));

  initial begin
    uvm_config_db#(virtual tb_clk_if)::set(null, "*", "clk_if", clk_if);
    run_test();
  end

  initial begin
    #1ms;
    `uvm_fatal("TB", "timeout -- simulation ran for 1ms with no test completion")
  end

endmodule
