// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// adc_ctrl -- COMPILE-CHECK TESTBENCH   (generated by IP/scripts/gen_tb.py)
//
// A skeleton, not a verification environment. It proves the RTL and its
// dependencies elaborate and a UVM test can start and finish. Every input
// is tied to a constant; nothing is stimulated and nothing is checked.
// Building the environment is the exercise -- see ../README.md.

module tb;

  import uvm_pkg::*;
  import adc_ctrl_test_pkg::*;
  import adc_ctrl_reg_pkg::*;
  `include "uvm_macros.svh"

  // Clocks. The main bus clock is 100 MHz to match Earl Grey; slow
  // domains (aon / core / usb) get their own so the ratio is realistic.
  logic clk, rst_n;

  initial begin
    clk = 1'b0;
    forever #5ns clk = ~clk;
  end

  logic clk_aon_i_tb;
  initial begin
    clk_aon_i_tb = 1'b0;
    forever #20ns clk_aon_i_tb = ~clk_aon_i_tb;
  end

  initial begin
    rst_n = 1'b0;
    repeat (10) @(posedge clk);
    rst_n = 1'b1;
  end

  // Port declarations. Inputs are tied to constants -- never floating.
  tlul_pkg::tl_h2d_t tl_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t tl_o ;
  prim_alert_pkg::alert_rx_t [NumAlerts-1:0] alert_rx_i = '{default: prim_alert_pkg::ALERT_RX_DEFAULT};
  prim_alert_pkg::alert_tx_t [NumAlerts-1:0] alert_tx_o ;
  ast_pkg::adc_ast_req_t adc_o ;
  ast_pkg::adc_ast_rsp_t adc_i = '0;
  logic intr_match_pending_o ;
  logic wkup_req_o ;

  adc_ctrl dut (
    .clk_i (clk),
    .clk_aon_i (clk_aon_i_tb),
    .rst_ni (rst_n),
    .rst_aon_ni (rst_n),
    .tl_i (tl_i),
    .tl_o (tl_o),
    .alert_rx_i (alert_rx_i),
    .alert_tx_o (alert_tx_o),
    .adc_o (adc_o),
    .adc_i (adc_i),
    .intr_match_pending_o (intr_match_pending_o),
    .wkup_req_o (wkup_req_o)
  );

  tb_clk_if clk_if (.clk(clk), .rst_n(rst_n));

  initial begin
    uvm_config_db#(virtual tb_clk_if)::set(null, "*", "clk_if", clk_if);
    run_test();
  end

  initial begin
    #1ms;
    `uvm_fatal("TB", "timeout -- simulation ran for 1ms with no test completion")
  end

endmodule
