// RTL-only compilation flist for usbdev.
// Includes the shared common infrastructure and the IP's own RTL.
//
// Usage (Xcelium example):
//   export IP_ROOT=/path/to/IP
//   xrun -f $IP_ROOT/flists/usbdev_rtl.f <your_tb_files>
//
// Generated by IP/scripts/gen_ip_flists.sh -- regenerate after adding IPs.

-f $IP_ROOT/common/common.f
-f $IP_ROOT/usbdev/rtl/files.f
