// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// pattgen -- COMPILE-CHECK TESTBENCH   (generated by IP/scripts/gen_tb.py)
//
// A skeleton, not a verification environment. It proves the RTL and its
// dependencies elaborate and a UVM test can start and finish. Every input
// is tied to a constant; nothing is stimulated and nothing is checked.
// Building the environment is the exercise -- see ../README.md.

module tb;

  import uvm_pkg::*;
  import pattgen_test_pkg::*;
  import pattgen_reg_pkg::*;
  `include "uvm_macros.svh"

  // Clocks. The main bus clock is 100 MHz to match Earl Grey; slow
  // domains (aon / core / usb) get their own so the ratio is realistic.
  logic clk, rst_n;

  initial begin
    clk = 1'b0;
    forever #5ns clk = ~clk;
  end

  initial begin
    rst_n = 1'b0;
    repeat (10) @(posedge clk);
    rst_n = 1'b1;
  end

  // Port declarations. Inputs are tied to constants -- never floating.
  tlul_pkg::tl_h2d_t tl_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t tl_o ;
  prim_alert_pkg::alert_rx_t [NumAlerts-1:0] alert_rx_i = '{default: prim_alert_pkg::ALERT_RX_DEFAULT};
  prim_alert_pkg::alert_tx_t [NumAlerts-1:0] alert_tx_o ;
  logic cio_pda0_tx_o ;
  logic cio_pcl0_tx_o ;
  logic cio_pda1_tx_o ;
  logic cio_pcl1_tx_o ;
  logic cio_pda0_tx_en_o ;
  logic cio_pcl0_tx_en_o ;
  logic cio_pda1_tx_en_o ;
  logic cio_pcl1_tx_en_o ;
  logic intr_done_ch0_o ;
  logic intr_done_ch1_o ;

  pattgen dut (
    .clk_i (clk),
    .rst_ni (rst_n),
    .tl_i (tl_i),
    .tl_o (tl_o),
    .alert_rx_i (alert_rx_i),
    .alert_tx_o (alert_tx_o),
    .cio_pda0_tx_o (cio_pda0_tx_o),
    .cio_pcl0_tx_o (cio_pcl0_tx_o),
    .cio_pda1_tx_o (cio_pda1_tx_o),
    .cio_pcl1_tx_o (cio_pcl1_tx_o),
    .cio_pda0_tx_en_o (cio_pda0_tx_en_o),
    .cio_pcl0_tx_en_o (cio_pcl0_tx_en_o),
    .cio_pda1_tx_en_o (cio_pda1_tx_en_o),
    .cio_pcl1_tx_en_o (cio_pcl1_tx_en_o),
    .intr_done_ch0_o (intr_done_ch0_o),
    .intr_done_ch1_o (intr_done_ch1_o)
  );

  tb_clk_if clk_if (.clk(clk), .rst_n(rst_n));

  initial begin
    uvm_config_db#(virtual tb_clk_if)::set(null, "*", "clk_if", clk_if);
    run_test();
  end

  initial begin
    #1ms;
    `uvm_fatal("TB", "timeout -- simulation ran for 1ms with no test completion")
  end

endmodule
