// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// spi_device -- COMPILE-CHECK TESTBENCH   (generated by IP/scripts/gen_tb.py)
//
// A skeleton, not a verification environment. It proves the RTL and its
// dependencies elaborate and a UVM test can start and finish. Every input
// is tied to a constant; nothing is stimulated and nothing is checked.
// Building the environment is the exercise -- see ../README.md.

module tb;

  import uvm_pkg::*;
  import spi_device_test_pkg::*;
  import spi_device_reg_pkg::*;
  `include "uvm_macros.svh"

  // Clocks. The main bus clock is 100 MHz to match Earl Grey; slow
  // domains (aon / core / usb) get their own so the ratio is realistic.
  logic clk, rst_n;

  initial begin
    clk = 1'b0;
    forever #5ns clk = ~clk;
  end

  initial begin
    rst_n = 1'b0;
    repeat (10) @(posedge clk);
    rst_n = 1'b1;
  end

  // Port declarations. Inputs are tied to constants -- never floating.
  tlul_pkg::tl_h2d_t tl_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t tl_o ;
  prim_alert_pkg::alert_rx_t [NumAlerts-1:0] alert_rx_i = '{default: prim_alert_pkg::ALERT_RX_DEFAULT};
  prim_alert_pkg::alert_tx_t [NumAlerts-1:0] alert_tx_o ;
  top_racl_pkg::racl_policy_vec_t racl_policies_i = top_racl_pkg::RACL_POLICY_VEC_DEFAULT;
  top_racl_pkg::racl_error_log_t racl_error_o ;
  logic cio_sck_i = '0;
  logic cio_csb_i = '0;
  logic [3:0] cio_sd_o ;
  logic [3:0] cio_sd_en_o ;
  [3:0] cio_sd_i = '0;
  logic cio_tpm_csb_i = '0;
  spi_device_pkg::passthrough_req_t passthrough_o ;
  spi_device_pkg::passthrough_rsp_t passthrough_i = '0;
  logic intr_upload_cmdfifo_not_empty_o ;
  logic intr_upload_payload_not_empty_o ;
  logic intr_upload_payload_overflow_o ;
  logic intr_readbuf_watermark_o ;
  logic intr_readbuf_flip_o ;
  logic intr_tpm_header_not_empty_o ;
  logic intr_tpm_rdfifo_cmd_end_o ;
  logic intr_tpm_rdfifo_drop_o ;
  prim_ram_2p_pkg::ram_2p_cfg_t ram_cfg_sys2spi_i = '0;
  prim_ram_2p_pkg::ram_2p_cfg_rsp_t ram_cfg_rsp_sys2spi_o ;
  prim_ram_2p_pkg::ram_2p_cfg_t ram_cfg_spi2sys_i = '0;
  prim_ram_2p_pkg::ram_2p_cfg_rsp_t ram_cfg_rsp_spi2sys_o ;
  logic sck_monitor_o ;
  logic mbist_en_i = '0;
  logic scan_clk_i = '0;
  logic scan_rst_ni = '0;
  prim_mubi_pkg::mubi4_t scanmode_i = '0;

  spi_device dut (
    .clk_i (clk),
    .rst_ni (rst_n),
    .tl_i (tl_i),
    .tl_o (tl_o),
    .alert_rx_i (alert_rx_i),
    .alert_tx_o (alert_tx_o),
    .racl_policies_i (racl_policies_i),
    .racl_error_o (racl_error_o),
    .cio_sck_i (cio_sck_i),
    .cio_csb_i (cio_csb_i),
    .cio_sd_o (cio_sd_o),
    .cio_sd_en_o (cio_sd_en_o),
    .cio_sd_i (cio_sd_i),
    .cio_tpm_csb_i (cio_tpm_csb_i),
    .passthrough_o (passthrough_o),
    .passthrough_i (passthrough_i),
    .intr_upload_cmdfifo_not_empty_o (intr_upload_cmdfifo_not_empty_o),
    .intr_upload_payload_not_empty_o (intr_upload_payload_not_empty_o),
    .intr_upload_payload_overflow_o (intr_upload_payload_overflow_o),
    .intr_readbuf_watermark_o (intr_readbuf_watermark_o),
    .intr_readbuf_flip_o (intr_readbuf_flip_o),
    .intr_tpm_header_not_empty_o (intr_tpm_header_not_empty_o),
    .intr_tpm_rdfifo_cmd_end_o (intr_tpm_rdfifo_cmd_end_o),
    .intr_tpm_rdfifo_drop_o (intr_tpm_rdfifo_drop_o),
    .ram_cfg_sys2spi_i (ram_cfg_sys2spi_i),
    .ram_cfg_rsp_sys2spi_o (ram_cfg_rsp_sys2spi_o),
    .ram_cfg_spi2sys_i (ram_cfg_spi2sys_i),
    .ram_cfg_rsp_spi2sys_o (ram_cfg_rsp_spi2sys_o),
    .sck_monitor_o (sck_monitor_o),
    .mbist_en_i (mbist_en_i),
    .scan_clk_i (scan_clk_i),
    .scan_rst_ni (scan_rst_ni),
    .scanmode_i (scanmode_i)
  );

  tb_clk_if clk_if (.clk(clk), .rst_n(rst_n));

  initial begin
    uvm_config_db#(virtual tb_clk_if)::set(null, "*", "clk_if", clk_if);
    run_test();
  end

  initial begin
    #1ms;
    `uvm_fatal("TB", "timeout -- simulation ran for 1ms with no test completion")
  end

endmodule
