// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// usbdev -- COMPILE-CHECK TESTBENCH   (generated by IP/scripts/gen_tb.py)
//
// A skeleton, not a verification environment. It proves the RTL and its
// dependencies elaborate and a UVM test can start and finish. Every input
// is tied to a constant; nothing is stimulated and nothing is checked.
// Building the environment is the exercise -- see ../README.md.

module tb;

  import uvm_pkg::*;
  import usbdev_test_pkg::*;
  import usbdev_pkg::*;
  import usbdev_reg_pkg::*;
  import prim_util_pkg::*;
  `include "uvm_macros.svh"

  // Clocks. The main bus clock is 100 MHz to match Earl Grey; slow
  // domains (aon / core / usb) get their own so the ratio is realistic.
  logic clk, rst_n;

  initial begin
    clk = 1'b0;
    forever #5ns clk = ~clk;
  end

  logic clk_aon_i_tb;
  initial begin
    clk_aon_i_tb = 1'b0;
    forever #20ns clk_aon_i_tb = ~clk_aon_i_tb;
  end

  initial begin
    rst_n = 1'b0;
    repeat (10) @(posedge clk);
    rst_n = 1'b1;
  end

  // Port declarations. Inputs are tied to constants -- never floating.
  tlul_pkg::tl_h2d_t tl_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t tl_o ;
  prim_alert_pkg::alert_rx_t [NumAlerts-1:0] alert_rx_i = '{default: prim_alert_pkg::ALERT_RX_DEFAULT};
  prim_alert_pkg::alert_tx_t [NumAlerts-1:0] alert_tx_o ;
  logic cio_usb_dp_i = '0;
  logic cio_usb_dn_i = '0;
  logic usb_rx_d_i = '0;
  logic cio_usb_dp_o ;
  logic cio_usb_dp_en_o ;
  logic cio_usb_dn_o ;
  logic cio_usb_dn_en_o ;
  logic usb_tx_se0_o ;
  logic usb_tx_d_o ;
  logic cio_sense_i = '0;
  logic usb_dp_pullup_o ;
  logic usb_dn_pullup_o ;
  logic usb_rx_enable_o ;
  logic usb_tx_use_d_se0_o ;
  logic usb_aon_suspend_req_o ;
  logic usb_aon_wake_ack_o ;
  logic usb_aon_bus_reset_i = '0;
  logic usb_aon_sense_lost_i = '0;
  logic usb_aon_bus_not_idle_i = '0;
  logic usb_aon_wake_detect_active_i = '0;
  logic usb_ref_val_o ;
  logic usb_ref_pulse_o ;
  prim_ram_1p_pkg::ram_1p_cfg_t ram_cfg_i = '0;
  prim_ram_1p_pkg::ram_1p_cfg_rsp_t ram_cfg_rsp_o ;
  logic intr_pkt_received_o ;
  logic intr_pkt_sent_o ;
  logic intr_powered_o ;
  logic intr_disconnected_o ;
  logic intr_host_lost_o ;
  logic intr_link_reset_o ;
  logic intr_link_suspend_o ;
  logic intr_link_resume_o ;
  logic intr_av_out_empty_o ;
  logic intr_rx_full_o ;
  logic intr_av_overflow_o ;
  logic intr_link_in_err_o ;
  logic intr_link_out_err_o ;
  logic intr_rx_crc_err_o ;
  logic intr_rx_pid_err_o ;
  logic intr_rx_bitstuff_err_o ;
  logic intr_frame_o ;
  logic intr_av_setup_empty_o ;

  usbdev dut (
    .clk_i (clk),
    .rst_ni (rst_n),
    .clk_aon_i (clk_aon_i_tb),
    .rst_aon_ni (rst_n),
    .tl_i (tl_i),
    .tl_o (tl_o),
    .alert_rx_i (alert_rx_i),
    .alert_tx_o (alert_tx_o),
    .cio_usb_dp_i (cio_usb_dp_i),
    .cio_usb_dn_i (cio_usb_dn_i),
    .usb_rx_d_i (usb_rx_d_i),
    .cio_usb_dp_o (cio_usb_dp_o),
    .cio_usb_dp_en_o (cio_usb_dp_en_o),
    .cio_usb_dn_o (cio_usb_dn_o),
    .cio_usb_dn_en_o (cio_usb_dn_en_o),
    .usb_tx_se0_o (usb_tx_se0_o),
    .usb_tx_d_o (usb_tx_d_o),
    .cio_sense_i (cio_sense_i),
    .usb_dp_pullup_o (usb_dp_pullup_o),
    .usb_dn_pullup_o (usb_dn_pullup_o),
    .usb_rx_enable_o (usb_rx_enable_o),
    .usb_tx_use_d_se0_o (usb_tx_use_d_se0_o),
    .usb_aon_suspend_req_o (usb_aon_suspend_req_o),
    .usb_aon_wake_ack_o (usb_aon_wake_ack_o),
    .usb_aon_bus_reset_i (usb_aon_bus_reset_i),
    .usb_aon_sense_lost_i (usb_aon_sense_lost_i),
    .usb_aon_bus_not_idle_i (usb_aon_bus_not_idle_i),
    .usb_aon_wake_detect_active_i (usb_aon_wake_detect_active_i),
    .usb_ref_val_o (usb_ref_val_o),
    .usb_ref_pulse_o (usb_ref_pulse_o),
    .ram_cfg_i (ram_cfg_i),
    .ram_cfg_rsp_o (ram_cfg_rsp_o),
    .intr_pkt_received_o (intr_pkt_received_o),
    .intr_pkt_sent_o (intr_pkt_sent_o),
    .intr_powered_o (intr_powered_o),
    .intr_disconnected_o (intr_disconnected_o),
    .intr_host_lost_o (intr_host_lost_o),
    .intr_link_reset_o (intr_link_reset_o),
    .intr_link_suspend_o (intr_link_suspend_o),
    .intr_link_resume_o (intr_link_resume_o),
    .intr_av_out_empty_o (intr_av_out_empty_o),
    .intr_rx_full_o (intr_rx_full_o),
    .intr_av_overflow_o (intr_av_overflow_o),
    .intr_link_in_err_o (intr_link_in_err_o),
    .intr_link_out_err_o (intr_link_out_err_o),
    .intr_rx_crc_err_o (intr_rx_crc_err_o),
    .intr_rx_pid_err_o (intr_rx_pid_err_o),
    .intr_rx_bitstuff_err_o (intr_rx_bitstuff_err_o),
    .intr_frame_o (intr_frame_o),
    .intr_av_setup_empty_o (intr_av_setup_empty_o)
  );

  tb_clk_if clk_if (.clk(clk), .rst_n(rst_n));

  initial begin
    uvm_config_db#(virtual tb_clk_if)::set(null, "*", "clk_if", clk_if);
    run_test();
  end

  initial begin
    #1ms;
    `uvm_fatal("TB", "timeout -- simulation ran for 1ms with no test completion")
  end

endmodule
