// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// mbx -- COMPILE-CHECK TESTBENCH   (generated by IP/scripts/gen_tb.py)
//
// A skeleton, not a verification environment. It proves the RTL and its
// dependencies elaborate and a UVM test can start and finish. Every input
// is tied to a constant; nothing is stimulated and nothing is checked.
// Building the environment is the exercise -- see ../README.md.

module tb;

  import uvm_pkg::*;
  import mbx_test_pkg::*;
  import tlul_pkg::*;
  import mbx_reg_pkg::*;
  `include "uvm_macros.svh"

  // Clocks. The main bus clock is 100 MHz to match Earl Grey; slow
  // domains (aon / core / usb) get their own so the ratio is realistic.
  logic clk, rst_n;

  initial begin
    clk = 1'b0;
    forever #5ns clk = ~clk;
  end

  initial begin
    rst_n = 1'b0;
    repeat (10) @(posedge clk);
    rst_n = 1'b1;
  end

  // Port declarations. Inputs are tied to constants -- never floating.
  logic intr_mbx_ready_o ;
  logic intr_mbx_abort_o ;
  logic intr_mbx_error_o ;
  logic doe_intr_support_o ;
  logic doe_intr_en_o ;
  logic doe_intr_o ;
  logic doe_async_msg_support_o ;
  prim_alert_pkg::alert_rx_t [NumAlerts-1:0] alert_rx_i = '{default: prim_alert_pkg::ALERT_RX_DEFAULT};
  prim_alert_pkg::alert_tx_t [NumAlerts-1:0] alert_tx_o ;
  top_racl_pkg::racl_policy_vec_t racl_policies_i = top_racl_pkg::RACL_POLICY_VEC_DEFAULT;
  top_racl_pkg::racl_error_log_t racl_error_o ;
  tlul_pkg::tl_h2d_t core_tl_d_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t core_tl_d_o ;
  tlul_pkg::tl_h2d_t soc_tl_d_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t soc_tl_d_o ;
  tlul_pkg::tl_d2h_t sram_tl_h_i = '0;
  tlul_pkg::tl_h2d_t sram_tl_h_o ;

  mbx dut (
    .clk_i (clk),
    .rst_ni (rst_n),
    .intr_mbx_ready_o (intr_mbx_ready_o),
    .intr_mbx_abort_o (intr_mbx_abort_o),
    .intr_mbx_error_o (intr_mbx_error_o),
    .doe_intr_support_o (doe_intr_support_o),
    .doe_intr_en_o (doe_intr_en_o),
    .doe_intr_o (doe_intr_o),
    .doe_async_msg_support_o (doe_async_msg_support_o),
    .alert_rx_i (alert_rx_i),
    .alert_tx_o (alert_tx_o),
    .racl_policies_i (racl_policies_i),
    .racl_error_o (racl_error_o),
    .core_tl_d_i (core_tl_d_i),
    .core_tl_d_o (core_tl_d_o),
    .soc_tl_d_i (soc_tl_d_i),
    .soc_tl_d_o (soc_tl_d_o),
    .sram_tl_h_i (sram_tl_h_i),
    .sram_tl_h_o (sram_tl_h_o)
  );

  tb_clk_if clk_if (.clk(clk), .rst_n(rst_n));

  initial begin
    uvm_config_db#(virtual tb_clk_if)::set(null, "*", "clk_if", clk_if);
    run_test();
  end

  initial begin
    #1ms;
    `uvm_fatal("TB", "timeout -- simulation ran for 1ms with no test completion")
  end

endmodule
