// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// dma -- COMPILE-CHECK TESTBENCH   (generated by IP/scripts/gen_tb.py)
//
// A skeleton, not a verification environment. It proves the RTL and its
// dependencies elaborate and a UVM test can start and finish. Every input
// is tied to a constant; nothing is stimulated and nothing is checked.
// Building the environment is the exercise -- see ../README.md.

module tb;

  import uvm_pkg::*;
  import dma_test_pkg::*;
  import tlul_pkg::*;
  import dma_pkg::*;
  import dma_reg_pkg::*;
  `include "uvm_macros.svh"

  // Clocks. The main bus clock is 100 MHz to match Earl Grey; slow
  // domains (aon / core / usb) get their own so the ratio is realistic.
  logic clk, rst_n;

  initial begin
    clk = 1'b0;
    forever #5ns clk = ~clk;
  end

  initial begin
    rst_n = 1'b0;
    repeat (10) @(posedge clk);
    rst_n = 1'b1;
  end

  // Port declarations. Inputs are tied to constants -- never floating.
  prim_mubi_pkg::mubi4_t scanmode_i = '0;
  logic intr_dma_done_o ;
  logic intr_dma_chunk_done_o ;
  logic intr_dma_error_o ;
  lsio_trigger_t lsio_trigger_i = '0;
  prim_alert_pkg::alert_rx_t [NumAlerts-1:0] alert_rx_i = '{default: prim_alert_pkg::ALERT_RX_DEFAULT};
  prim_alert_pkg::alert_tx_t [NumAlerts-1:0] alert_tx_o ;
  top_racl_pkg::racl_policy_vec_t racl_policies_i = top_racl_pkg::RACL_POLICY_VEC_DEFAULT;
  top_racl_pkg::racl_error_log_t racl_error_o ;
  tlul_pkg::tl_h2d_t tl_d_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t tl_d_o ;
  tlul_pkg::tl_d2h_t ctn_tl_d2h_i = '0;
  tlul_pkg::tl_h2d_t ctn_tl_h2d_o ;
  tlul_pkg::tl_d2h_t host_tl_h_i = '0;
  tlul_pkg::tl_h2d_t host_tl_h_o ;
  dma_pkg::sys_rsp_t sys_i = '0;
  dma_pkg::sys_req_t sys_o ;

  dma dut (
    .clk_i (clk),
    .rst_ni (rst_n),
    .scanmode_i (scanmode_i),
    .intr_dma_done_o (intr_dma_done_o),
    .intr_dma_chunk_done_o (intr_dma_chunk_done_o),
    .intr_dma_error_o (intr_dma_error_o),
    .lsio_trigger_i (lsio_trigger_i),
    .alert_rx_i (alert_rx_i),
    .alert_tx_o (alert_tx_o),
    .racl_policies_i (racl_policies_i),
    .racl_error_o (racl_error_o),
    .tl_d_i (tl_d_i),
    .tl_d_o (tl_d_o),
    .ctn_tl_d2h_i (ctn_tl_d2h_i),
    .ctn_tl_h2d_o (ctn_tl_h2d_o),
    .host_tl_h_i (host_tl_h_i),
    .host_tl_h_o (host_tl_h_o),
    .sys_i (sys_i),
    .sys_o (sys_o)
  );

  tb_clk_if clk_if (.clk(clk), .rst_n(rst_n));

  initial begin
    uvm_config_db#(virtual tb_clk_if)::set(null, "*", "clk_if", clk_if);
    run_test();
  end

  initial begin
    #1ms;
    `uvm_fatal("TB", "timeout -- simulation ran for 1ms with no test completion")
  end

endmodule
