// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// rv_dm -- COMPILE-CHECK TESTBENCH   (generated by IP/scripts/gen_tb.py)
//
// A skeleton, not a verification environment. It proves the RTL and its
// dependencies elaborate and a UVM test can start and finish. Every input
// is tied to a constant; nothing is stimulated and nothing is checked.
// Building the environment is the exercise -- see ../README.md.

module tb;

  import uvm_pkg::*;
  import rv_dm_test_pkg::*;
  import rv_dm_reg_pkg::*;
  `include "uvm_macros.svh"

  // Clocks. The main bus clock is 100 MHz to match Earl Grey; slow
  // domains (aon / core / usb) get their own so the ratio is realistic.
  logic clk, rst_n;

  initial begin
    clk = 1'b0;
    forever #5ns clk = ~clk;
  end

  logic clk_lc_i_tb;
  initial begin
    clk_lc_i_tb = 1'b0;
    forever #20ns clk_lc_i_tb = ~clk_lc_i_tb;
  end

  initial begin
    rst_n = 1'b0;
    repeat (10) @(posedge clk);
    rst_n = 1'b1;
  end

  // Port declarations. Inputs are tied to constants -- never floating.
  logic [31:0] next_dm_addr_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_hw_debug_clr_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_hw_debug_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_dft_en_i = '0;
  lc_ctrl_pkg::lc_tx_t pinmux_hw_debug_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_check_byp_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_escalate_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_init_done_i = '0;
  logic strap_en_i = '0;
  logic strap_en_override_i = '0;
  prim_mubi_pkg::mubi8_t otp_dis_rv_dm_late_debug_i = '0;
  prim_mubi_pkg::mubi4_t scanmode_i = '0;
  logic scan_rst_ni = '0;
  logic ndmreset_req_o ;
  logic dmactive_o ;
  logic [NrHarts-1:0] debug_req_o ;
  logic [NrHarts-1:0] unavailable_i = '0;
  tlul_pkg::tl_h2d_t regs_tl_d_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t regs_tl_d_o ;
  tlul_pkg::tl_h2d_t mem_tl_d_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t mem_tl_d_o ;
  tlul_pkg::tl_h2d_t sba_tl_h_o ;
  tlul_pkg::tl_d2h_t sba_tl_h_i = '0;
  prim_alert_pkg::alert_rx_t [NumAlerts-1:0] alert_rx_i = '{default: prim_alert_pkg::ALERT_RX_DEFAULT};
  prim_alert_pkg::alert_tx_t [NumAlerts-1:0] alert_tx_o ;
  top_racl_pkg::racl_policy_vec_t racl_policies_i = top_racl_pkg::RACL_POLICY_VEC_DEFAULT;
  top_racl_pkg::racl_error_log_t racl_error_o ;
  jtag_pkg::jtag_req_t jtag_i = '0;
  jtag_pkg::jtag_rsp_t jtag_o ;
  tlul_pkg::tl_h2d_t dbg_tl_d_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t dbg_tl_d_o ;

  rv_dm dut (
    .clk_i (clk),
    .clk_lc_i (clk_lc_i_tb),
    .rst_ni (rst_n),
    .rst_lc_ni (rst_n),
    .next_dm_addr_i (next_dm_addr_i),
    .lc_hw_debug_clr_i (lc_hw_debug_clr_i),
    .lc_hw_debug_en_i (lc_hw_debug_en_i),
    .lc_dft_en_i (lc_dft_en_i),
    .pinmux_hw_debug_en_i (pinmux_hw_debug_en_i),
    .lc_check_byp_en_i (lc_check_byp_en_i),
    .lc_escalate_en_i (lc_escalate_en_i),
    .lc_init_done_i (lc_init_done_i),
    .strap_en_i (strap_en_i),
    .strap_en_override_i (strap_en_override_i),
    .otp_dis_rv_dm_late_debug_i (otp_dis_rv_dm_late_debug_i),
    .scanmode_i (scanmode_i),
    .scan_rst_ni (scan_rst_ni),
    .ndmreset_req_o (ndmreset_req_o),
    .dmactive_o (dmactive_o),
    .debug_req_o (debug_req_o),
    .unavailable_i (unavailable_i),
    .regs_tl_d_i (regs_tl_d_i),
    .regs_tl_d_o (regs_tl_d_o),
    .mem_tl_d_i (mem_tl_d_i),
    .mem_tl_d_o (mem_tl_d_o),
    .sba_tl_h_o (sba_tl_h_o),
    .sba_tl_h_i (sba_tl_h_i),
    .alert_rx_i (alert_rx_i),
    .alert_tx_o (alert_tx_o),
    .racl_policies_i (racl_policies_i),
    .racl_error_o (racl_error_o),
    .jtag_i (jtag_i),
    .jtag_o (jtag_o),
    .dbg_tl_d_i (dbg_tl_d_i),
    .dbg_tl_d_o (dbg_tl_d_o)
  );

  tb_clk_if clk_if (.clk(clk), .rst_n(rst_n));

  initial begin
    uvm_config_db#(virtual tb_clk_if)::set(null, "*", "clk_if", clk_if);
    run_test();
  end

  initial begin
    #1ms;
    `uvm_fatal("TB", "timeout -- simulation ran for 1ms with no test completion")
  end

endmodule
