// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// pwrmgr -- COMPILE-CHECK TESTBENCH   (generated by IP/scripts/gen_tb.py)
//
// A skeleton, not a verification environment. It proves the RTL and its
// dependencies elaborate and a UVM test can start and finish. Every input
// is tied to a constant; nothing is stimulated and nothing is checked.
// Building the environment is the exercise -- see ../README.md.

module tb;

  import uvm_pkg::*;
  import pwrmgr_test_pkg::*;
  import pwrmgr_pkg::*;
  import pwrmgr_reg_pkg::*;
  `include "uvm_macros.svh"

  // Clocks. The main bus clock is 100 MHz to match Earl Grey; slow
  // domains (aon / core / usb) get their own so the ratio is realistic.
  logic clk, rst_n;

  initial begin
    clk = 1'b0;
    forever #5ns clk = ~clk;
  end

  logic clk_slow_i_tb;
  initial begin
    clk_slow_i_tb = 1'b0;
    forever #20ns clk_slow_i_tb = ~clk_slow_i_tb;
  end

  logic clk_lc_i_tb;
  initial begin
    clk_lc_i_tb = 1'b0;
    forever #20ns clk_lc_i_tb = ~clk_lc_i_tb;
  end

  logic clk_esc_i_tb;
  initial begin
    clk_esc_i_tb = 1'b0;
    forever #20ns clk_esc_i_tb = ~clk_esc_i_tb;
  end

  initial begin
    rst_n = 1'b0;
    repeat (10) @(posedge clk);
    rst_n = 1'b1;
  end

  // Port declarations. Inputs are tied to constants -- never floating.
  tlul_pkg::tl_h2d_t tl_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t tl_o ;
  prim_alert_pkg::alert_rx_t [NumAlerts-1:0] alert_rx_i = '{default: prim_alert_pkg::ALERT_RX_DEFAULT};
  prim_alert_pkg::alert_tx_t [NumAlerts-1:0] alert_tx_o ;
  pwr_ast_rsp_t pwr_ast_i = '0;
  pwr_ast_req_t pwr_ast_o ;
  pwr_rst_rsp_t pwr_rst_i = '0;
  pwr_rst_req_t pwr_rst_o ;
  pwr_clk_req_t pwr_clk_o ;
  pwr_clk_rsp_t pwr_clk_i = '0;
  pwr_otp_rsp_t pwr_otp_i = '0;
  pwr_otp_req_t pwr_otp_o ;
  lc_ctrl_pkg::pwr_lc_rsp_t pwr_lc_i = '0;
  lc_ctrl_pkg::pwr_lc_req_t pwr_lc_o ;
  pwr_nvm_t pwr_nvm_i = '0;
  rv_core_ibex_pkg::cpu_pwrmgr_t pwr_cpu_i = '0;
  lc_ctrl_pkg::lc_tx_t fetch_en_o ;
  lc_ctrl_pkg::lc_tx_t lc_hw_debug_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_dft_en_i = '0;
  [NumWkups-1:0] wakeups_i = '0;
  [NumRstReqs-1:0] rstreqs_i = '0;
  logic ndmreset_req_i = '0;
  logic strap_o ;
  logic low_power_o ;
  rom_ctrl_pkg::pwrmgr_data_t [NumRomInputs-1:0] rom_ctrl_i = '0;
  prim_mubi_pkg::mubi4_t sw_rst_req_i = '0;
  prim_esc_pkg::esc_tx_t esc_rst_tx_i = '0;
  prim_esc_pkg::esc_rx_t esc_rst_rx_o ;
  logic intr_wakeup_o ;

  pwrmgr dut (
    .clk_slow_i (clk_slow_i_tb),
    .clk_i (clk),
    .rst_slow_ni (rst_n),
    .rst_ni (rst_n),
    .rst_main_ni (rst_n),
    .clk_lc_i (clk_lc_i_tb),
    .rst_lc_ni (rst_n),
    .clk_esc_i (clk_esc_i_tb),
    .rst_esc_ni (rst_n),
    .tl_i (tl_i),
    .tl_o (tl_o),
    .alert_rx_i (alert_rx_i),
    .alert_tx_o (alert_tx_o),
    .pwr_ast_i (pwr_ast_i),
    .pwr_ast_o (pwr_ast_o),
    .pwr_rst_i (pwr_rst_i),
    .pwr_rst_o (pwr_rst_o),
    .pwr_clk_o (pwr_clk_o),
    .pwr_clk_i (pwr_clk_i),
    .pwr_otp_i (pwr_otp_i),
    .pwr_otp_o (pwr_otp_o),
    .pwr_lc_i (pwr_lc_i),
    .pwr_lc_o (pwr_lc_o),
    .pwr_nvm_i (pwr_nvm_i),
    .pwr_cpu_i (pwr_cpu_i),
    .fetch_en_o (fetch_en_o),
    .lc_hw_debug_en_i (lc_hw_debug_en_i),
    .lc_dft_en_i (lc_dft_en_i),
    .wakeups_i (wakeups_i),
    .rstreqs_i (rstreqs_i),
    .ndmreset_req_i (ndmreset_req_i),
    .strap_o (strap_o),
    .low_power_o (low_power_o),
    .rom_ctrl_i (rom_ctrl_i),
    .sw_rst_req_i (sw_rst_req_i),
    .esc_rst_tx_i (esc_rst_tx_i),
    .esc_rst_rx_o (esc_rst_rx_o),
    .intr_wakeup_o (intr_wakeup_o)
  );

  tb_clk_if clk_if (.clk(clk), .rst_n(rst_n));

  initial begin
    uvm_config_db#(virtual tb_clk_if)::set(null, "*", "clk_if", clk_if);
    run_test();
  end

  initial begin
    #1ms;
    `uvm_fatal("TB", "timeout -- simulation ran for 1ms with no test completion")
  end

endmodule
