// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// flash_ctrl -- COMPILE-CHECK TESTBENCH   (generated by IP/scripts/gen_tb.py)
//
// A skeleton, not a verification environment. It proves the RTL and its
// dependencies elaborate and a UVM test can start and finish. Every input
// is tied to a constant; nothing is stimulated and nothing is checked.
// Building the environment is the exercise -- see ../README.md.

module tb;

  import uvm_pkg::*;
  import flash_ctrl_test_pkg::*;
  import flash_ctrl_top_specific_pkg::*;
  import flash_ctrl_reg_pkg::*;
  `include "uvm_macros.svh"

  // Clocks. The main bus clock is 100 MHz to match Earl Grey; slow
  // domains (aon / core / usb) get their own so the ratio is realistic.
  logic clk, rst_n;

  initial begin
    clk = 1'b0;
    forever #5ns clk = ~clk;
  end

  logic clk_otp_i_tb;
  initial begin
    clk_otp_i_tb = 1'b0;
    forever #5ns clk_otp_i_tb = ~clk_otp_i_tb;
  end

  initial begin
    rst_n = 1'b0;
    repeat (10) @(posedge clk);
    rst_n = 1'b1;
  end

  // Port declarations. Inputs are tied to constants -- never floating.
  lc_ctrl_pkg::lc_tx_t lc_creator_seed_sw_rw_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_owner_seed_sw_rw_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_iso_part_sw_rd_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_iso_part_sw_wr_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_seed_hw_rd_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_escalate_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_nvm_debug_en_i = '0;
  tlul_pkg::tl_h2d_t core_tl_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t core_tl_o ;
  tlul_pkg::tl_h2d_t prim_tl_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t prim_tl_o ;
  tlul_pkg::tl_h2d_t mem_tl_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t mem_tl_o ;
  otp_ctrl_pkg::nvm_otp_key_req_t otp_o ;
  otp_ctrl_pkg::nvm_otp_key_rsp_t otp_i = '0;
  lc_ctrl_pkg::lc_tx_t rma_req_i = '0;
  lc_ctrl_pkg::lc_nvm_rma_seed_t rma_seed_i = '0;
  lc_ctrl_pkg::lc_tx_t rma_ack_o ;
  pwrmgr_pkg::pwr_nvm_t pwrmgr_o ;
  keymgr_flash_t keymgr_o ;
  logic cio_tck_i = '0;
  logic cio_tms_i = '0;
  logic cio_tdi_i = '0;
  logic cio_tdo_en_o ;
  logic cio_tdo_o ;
  logic intr_corr_err_o ;
  logic intr_prog_empty_o ;
  logic intr_prog_lvl_o ;
  logic intr_rd_full_o ;
  logic intr_rd_lvl_o ;
  logic intr_op_done_o ;
  prim_alert_pkg::alert_rx_t [flash_ctrl_reg_pkg::NumAlerts-1:0] alert_rx_i = '{default: prim_alert_pkg::ALERT_RX_DEFAULT};
  prim_alert_pkg::alert_tx_t [flash_ctrl_reg_pkg::NumAlerts-1:0] alert_tx_o ;
  ast_pkg::ast_obs_ctrl_t obs_ctrl_i = '0;
  logic [7:0] fla_obs_o ;
  logic scan_en_i = '0;
  prim_mubi_pkg::mubi4_t scanmode_i = '0;
  logic scan_rst_ni = '0;
  prim_mubi_pkg::mubi4_t flash_bist_enable_i = '0;
  logic flash_power_down_h_i = '0;
  logic flash_power_ready_h_i = '0;
  wire flash_test_mode_a_io ;
  wire flash_test_voltage_h_io ;

  flash_ctrl dut (
    .clk_i (clk),
    .rst_ni (rst_n),
    .rst_shadowed_ni (rst_n),
    .clk_otp_i (clk_otp_i_tb),
    .rst_otp_ni (rst_n),
    .lc_creator_seed_sw_rw_en_i (lc_creator_seed_sw_rw_en_i),
    .lc_owner_seed_sw_rw_en_i (lc_owner_seed_sw_rw_en_i),
    .lc_iso_part_sw_rd_en_i (lc_iso_part_sw_rd_en_i),
    .lc_iso_part_sw_wr_en_i (lc_iso_part_sw_wr_en_i),
    .lc_seed_hw_rd_en_i (lc_seed_hw_rd_en_i),
    .lc_escalate_en_i (lc_escalate_en_i),
    .lc_nvm_debug_en_i (lc_nvm_debug_en_i),
    .core_tl_i (core_tl_i),
    .core_tl_o (core_tl_o),
    .prim_tl_i (prim_tl_i),
    .prim_tl_o (prim_tl_o),
    .mem_tl_i (mem_tl_i),
    .mem_tl_o (mem_tl_o),
    .otp_o (otp_o),
    .otp_i (otp_i),
    .rma_req_i (rma_req_i),
    .rma_seed_i (rma_seed_i),
    .rma_ack_o (rma_ack_o),
    .pwrmgr_o (pwrmgr_o),
    .keymgr_o (keymgr_o),
    .cio_tck_i (cio_tck_i),
    .cio_tms_i (cio_tms_i),
    .cio_tdi_i (cio_tdi_i),
    .cio_tdo_en_o (cio_tdo_en_o),
    .cio_tdo_o (cio_tdo_o),
    .intr_corr_err_o (intr_corr_err_o),
    .intr_prog_empty_o (intr_prog_empty_o),
    .intr_prog_lvl_o (intr_prog_lvl_o),
    .intr_rd_full_o (intr_rd_full_o),
    .intr_rd_lvl_o (intr_rd_lvl_o),
    .intr_op_done_o (intr_op_done_o),
    .alert_rx_i (alert_rx_i),
    .alert_tx_o (alert_tx_o),
    .obs_ctrl_i (obs_ctrl_i),
    .fla_obs_o (fla_obs_o),
    .scan_en_i (scan_en_i),
    .scanmode_i (scanmode_i),
    .scan_rst_ni (scan_rst_ni),
    .flash_bist_enable_i (flash_bist_enable_i),
    .flash_power_down_h_i (flash_power_down_h_i),
    .flash_power_ready_h_i (flash_power_ready_h_i),
    .flash_test_mode_a_io (flash_test_mode_a_io),
    .flash_test_voltage_h_io (flash_test_voltage_h_io)
  );

  tb_clk_if clk_if (.clk(clk), .rst_n(rst_n));

  initial begin
    uvm_config_db#(virtual tb_clk_if)::set(null, "*", "clk_if", clk_if);
    run_test();
  end

  initial begin
    #1ms;
    `uvm_fatal("TB", "timeout -- simulation ran for 1ms with no test completion")
  end

endmodule
