#!/usr/bin/env bash
# scripts/setup_host_shims.sh
#
# Idempotently prepare the machine-local library/pkg-config shims that the
# OpenTitan Bazel SW build needs on this RHEL9 host (no sudo, no *-devel pkgs):
#
#   ~/.local/lib64/
#     libssl.so    -> /usr/lib64/libssl.so.3      (dev symlink, openssl-devel stand-in)
#     libcrypto.so -> /usr/lib64/libcrypto.so.3   (dev symlink)
#     libudev.so   -> /usr/lib64/libudev.so.1     (dev symlink, systemd-devel stand-in)
#     libftdi1.so  -> stub built from scripts/libftdi1_stub.c (host has no libftdi;
#                     opentitantool's FTDI transport is dead code in simulation)
#     pkgconfig/   -> openssl.pc, libssl.pc, libcrypto.pc, libudev.pc with
#                     libdir=~/.local/lib64 and includedir=<IC251 OpenSSL 3 headers>
#
# The .bazelrc-site generated by activate_env.sh points OT's
# --//third_party/rust:openssl_pkg_config_path at this pkgconfig dir.
#
# Safe to re-run any time.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIBDIR="${HOME}/.local/lib64"
PCDIR="${LIBDIR}/pkgconfig"
OSSL_INC="${HOME}/tools/install/IC251/tools.lnx86/atlas/python3.12/prefix/include"

mkdir -p "${PCDIR}"

# --- dev symlinks --------------------------------------------------------------
ln -sf /usr/lib64/libssl.so.3    "${LIBDIR}/libssl.so"
ln -sf /usr/lib64/libcrypto.so.3 "${LIBDIR}/libcrypto.so"
ln -sf /usr/lib64/libudev.so.1   "${LIBDIR}/libudev.so"

# --- libftdi1 stub -------------------------------------------------------------
# STATIC archive on purpose: with only libftdi1.a on the -L path, ld links the
# stub into opentitantool directly — no NEEDED libftdi1.so entry, so the
# binary runs in Bazel sandboxes that scrub LD_LIBRARY_PATH (`env -`).
rm -f "${LIBDIR}/libftdi1.so"
if [[ ! -e "${LIBDIR}/libftdi1.a" || "${SCRIPT_DIR}/libftdi1_stub.c" -nt "${LIBDIR}/libftdi1.a" ]]; then
    gcc -c -fPIC -o /tmp/libftdi1_stub.o "${SCRIPT_DIR}/libftdi1_stub.c"
    ar rcs "${LIBDIR}/libftdi1.a" /tmp/libftdi1_stub.o
    rm -f /tmp/libftdi1_stub.o
    echo "built ${LIBDIR}/libftdi1.a (static stub)"
fi

# --- pkg-config shims ----------------------------------------------------------
cat > "${PCDIR}/openssl.pc" <<EOF
prefix=/usr
exec_prefix=\${prefix}
libdir=${LIBDIR}
includedir=${OSSL_INC}

Name: OpenSSL
Description: Secure Sockets Layer and cryptography libraries (shim)
Version: 3.0.14
Requires.private: libssl libcrypto
Libs: -L\${libdir} -lssl -lcrypto
Libs.private: -ldl -lpthread
Cflags: -I\${includedir}
EOF

cat > "${PCDIR}/libssl.pc" <<EOF
prefix=/usr
exec_prefix=\${prefix}
libdir=${LIBDIR}
includedir=${OSSL_INC}

Name: OpenSSL-libssl
Description: Secure Sockets Layer library (shim)
Version: 3.0.14
Requires.private: libcrypto
Libs: -L\${libdir} -lssl
Cflags: -I\${includedir}
EOF

cat > "${PCDIR}/libcrypto.pc" <<EOF
prefix=/usr
exec_prefix=\${prefix}
libdir=${LIBDIR}
includedir=${OSSL_INC}

Name: OpenSSL-libcrypto
Description: OpenSSL cryptography library (shim)
Version: 3.0.14
Libs: -L\${libdir} -lcrypto
Libs.private: -ldl -lpthread
Cflags: -I\${includedir}
EOF

cat > "${PCDIR}/libudev.pc" <<EOF
prefix=/usr
exec_prefix=\${prefix}
libdir=${LIBDIR}
includedir=${HOME}/.local/include

Name: libudev
Description: udev library stub for OpenTitan Bazel build
Version: 248
Libs: -L\${libdir} -ludev
Cflags: -I\${includedir}
EOF

echo "host shims ready under ${LIBDIR} (pkgconfig: ${PCDIR})"
