#!/usr/bin/env bash
# Regenerate IP/common/common.f — the shared dependency filelist.
#
# Run this after re-copying IP/common/rtl from the vendor tree. It is
# deterministic: packages first in dependency order, then every remaining
# module in alphabetical order.
#
# Usage: ./IP/scripts/gen_common_f.sh
set -euo pipefail

IP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RTL="$IP_ROOT/common/rtl"
OUT="$IP_ROOT/common/common.f"

# Packages must compile before anything that scope-resolves into them.
# Order verified from the `<pkg>::` references in each file:
#   tlul_pkg     -> top_pkg, prim_mubi_pkg, prim_secded_pkg
#   top_racl_pkg -> top_pkg, prim_util_pkg, tlul_pkg
ORDERED_PKGS=(
  top/top_pkg.sv
  prim/prim_util_pkg.sv
  prim/prim_secded_pkg.sv
  prim/prim_mubi_pkg.sv
  prim/prim_alert_pkg.sv
  prim/prim_esc_pkg.sv
  prim/prim_subreg_pkg.sv
  prim/prim_count_pkg.sv
  prim/prim_cipher_pkg.sv
  prim/prim_pad_wrapper_pkg.sv
  prim/prim_ascon_pkg.sv
  prim/prim_sha2_pkg.sv
  prim/prim_trivium_pkg.sv
  prim_generic/prim_pkg.sv
  prim_generic/prim_ram_1p_pkg.sv
  prim_generic/prim_ram_2p_pkg.sv
  prim_generic/prim_rom_pkg.sv
  tlul/tlul_pkg.sv
  top/top_racl_pkg.sv
)

# Not every file in prim/ and tlul/ is generic substrate. These 14 belong to a
# specific IP and scope-resolve into that IP's package, which is not part of
# common/. Compiling them here produced 129 errors on the first run
# (2026-08-20) -- all of them in files that neither uart nor gpio instantiate.
#
# If you add an IP that DOES need one of these (most security IPs use
# prim_lc_sync), add both the prim file and the package it needs to that IP's
# own rtl/files.f rather than putting them back here.
#
#   file                        needs
#   --------------------------  ---------------------------------
#   prim_lc_*                   lc_ctrl_pkg
#   tlul_lc_gate                lc_ctrl_pkg
#   prim_edn_req                edn_pkg
#   prim_flash                  flash_ctrl_top_specific_pkg
#   prim_generic_flash_bank     flash_phy_pkg
#   tlul_jtag_dtm               jtag_pkg
#   tlul_adapter_dmi            dm (rv_dm package)
#   tlul_adapter_vh             ast_pkg
#   prim_sdc_example            ast_pkg -- an SDC timing example, not RTL
EXCLUDE=(
  prim/prim_lc_and_hardened.sv
  prim/prim_lc_combine.sv
  prim/prim_lc_dec.sv
  prim/prim_lc_or_hardened.sv
  prim/prim_lc_sender.sv
  prim/prim_lc_sync.sv
  prim/prim_edn_req.sv
  prim/prim_sdc_example.sv
  prim_generic/prim_flash.sv
  prim_generic/prim_generic_flash_bank.sv
  tlul/tlul_lc_gate.sv
  tlul/tlul_jtag_dtm.sv
  tlul/tlul_adapter_dmi.sv
  tlul/tlul_adapter_vh.sv
)

is_excluded() {
  printf '%s\n' "${EXCLUDE[@]}" | grep -qx "$1"
}

{
  echo "// Generated by IP/scripts/gen_common_f.sh -- do not edit by hand."
  echo "// Shared dependencies for every standalone IP compile:"
  echo "//   prim (primitives), prim_generic (concrete impls of the abstract"
  echo "//   prims), tlul (TileLink-UL fabric), and the Earl Grey top packages."
  echo
  echo "// -- include paths (prim_assert.sv pulls in the .svh macro files) --"
  echo "+incdir+\$IP_ROOT/common/rtl/prim"
  echo "+incdir+\$IP_ROOT/common/rtl/prim_generic"
  echo "+incdir+\$IP_ROOT/common/rtl/tlul"
  echo
  echo "// -- packages, in dependency order --"
  for p in "${ORDERED_PKGS[@]}"; do
    [[ -f "$RTL/$p" ]] || { echo "missing package: $p" >&2; exit 1; }
    echo "\$IP_ROOT/common/rtl/$p"
  done
  echo
  echo "// -- everything else --"
  for d in prim prim_generic tlul top; do
    for f in "$RTL/$d"/*.sv; do
      rel="$d/$(basename "$f")"
      # skip the packages already emitted above
      printf '%s\n' "${ORDERED_PKGS[@]}" | grep -qx "$rel" && continue
      # skip IP-specific files that need packages common/ does not carry
      is_excluded "$rel" && continue
      echo "\$IP_ROOT/common/rtl/$rel"
    done
  done
} > "$OUT"

echo "wrote $OUT ($(grep -c '^\$IP_ROOT.*\.sv$' "$OUT") files)"
