#!/usr/bin/env bash
# Generate IP/flists/<ip>_rtl.f for every IP under IP/.
# Usage: bash IP/scripts/gen_ip_flists.sh
# Run from the repo root or from anywhere -- uses the script's own location.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
FLIST_DIR="$IP_DIR/flists"
mkdir -p "$FLIST_DIR"

SKIP=(common scripts flists)

generated=0
for ip_path in "$IP_DIR"/*/; do
  ip="$(basename "$ip_path")"
  # skip non-IP dirs
  for s in "${SKIP[@]}"; do [[ "$ip" == "$s" ]] && continue 2; done
  [[ -f "$ip_path/rtl/files.f" ]] || continue

  out="$FLIST_DIR/${ip}_rtl.f"
  cat > "$out" <<FLIST
// RTL-only compilation flist for ${ip}.
// Includes the shared common infrastructure and the IP's own RTL.
//
// Usage (Xcelium example):
//   export IP_ROOT=/path/to/IP
//   xrun -f \$IP_ROOT/flists/${ip}_rtl.f <your_tb_files>
//
// Generated by IP/scripts/gen_ip_flists.sh -- regenerate after adding IPs.

-f \$IP_ROOT/common/common.f
-f \$IP_ROOT/${ip}/rtl/files.f
FLIST
  echo "  wrote ${ip}_rtl.f"
  generated=$((generated + 1))
done

echo "Done — $generated flist(s) written to $FLIST_DIR"
