// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// otbn -- COMPILE-CHECK TESTBENCH   (generated by IP/scripts/gen_tb.py)
//
// A skeleton, not a verification environment. It proves the RTL and its
// dependencies elaborate and a UVM test can start and finish. Every input
// is tied to a constant; nothing is stimulated and nothing is checked.
// Building the environment is the exercise -- see ../README.md.

module tb;

  import uvm_pkg::*;
  import otbn_test_pkg::*;
  import prim_alert_pkg::*;
  import otbn_pkg::*;
  import otbn_reg_pkg::*;
  `include "uvm_macros.svh"

  // Clocks. The main bus clock is 100 MHz to match Earl Grey; slow
  // domains (aon / core / usb) get their own so the ratio is realistic.
  logic clk, rst_n;

  initial begin
    clk = 1'b0;
    forever #5ns clk = ~clk;
  end

  logic clk_edn_i_tb;
  initial begin
    clk_edn_i_tb = 1'b0;
    forever #5ns clk_edn_i_tb = ~clk_edn_i_tb;
  end

  logic clk_otp_i_tb;
  initial begin
    clk_otp_i_tb = 1'b0;
    forever #5ns clk_otp_i_tb = ~clk_otp_i_tb;
  end

  initial begin
    rst_n = 1'b0;
    repeat (10) @(posedge clk);
    rst_n = 1'b1;
  end

  // Port declarations. Inputs are tied to constants -- never floating.
  tlul_pkg::tl_h2d_t tl_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t tl_o ;
  prim_mubi_pkg::mubi4_t idle_o ;
  logic intr_done_o ;
  prim_alert_pkg::alert_rx_t [NumAlerts-1:0] alert_rx_i = '{default: prim_alert_pkg::ALERT_RX_DEFAULT};
  prim_alert_pkg::alert_tx_t [NumAlerts-1:0] alert_tx_o ;
  lc_ctrl_pkg::lc_tx_t lc_escalate_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_rma_req_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_rma_ack_o ;
  prim_ram_1p_pkg::ram_1p_cfg_t ram_cfg_imem_i = '0;
  prim_ram_1p_pkg::ram_1p_cfg_t ram_cfg_dmem_i = '0;
  prim_ram_1p_pkg::ram_1p_cfg_rsp_t ram_cfg_rsp_imem_o ;
  prim_ram_1p_pkg::ram_1p_cfg_rsp_t ram_cfg_rsp_dmem_o ;
  edn_pkg::edn_req_t edn_rnd_o ;
  edn_pkg::edn_rsp_t edn_rnd_i = '0;
  edn_pkg::edn_req_t edn_urnd_o ;
  edn_pkg::edn_rsp_t edn_urnd_i = '0;
  otp_ctrl_pkg::otbn_otp_key_req_t otbn_otp_key_o ;
  otp_ctrl_pkg::otbn_otp_key_rsp_t otbn_otp_key_i = '0;
  keymgr_pkg::otbn_key_req_t keymgr_key_i = '0;

  otbn dut (
    .clk_i (clk),
    .rst_ni (rst_n),
    .tl_i (tl_i),
    .tl_o (tl_o),
    .idle_o (idle_o),
    .intr_done_o (intr_done_o),
    .alert_rx_i (alert_rx_i),
    .alert_tx_o (alert_tx_o),
    .lc_escalate_en_i (lc_escalate_en_i),
    .lc_rma_req_i (lc_rma_req_i),
    .lc_rma_ack_o (lc_rma_ack_o),
    .ram_cfg_imem_i (ram_cfg_imem_i),
    .ram_cfg_dmem_i (ram_cfg_dmem_i),
    .ram_cfg_rsp_imem_o (ram_cfg_rsp_imem_o),
    .ram_cfg_rsp_dmem_o (ram_cfg_rsp_dmem_o),
    .clk_edn_i (clk_edn_i_tb),
    .rst_edn_ni (rst_n),
    .edn_rnd_o (edn_rnd_o),
    .edn_rnd_i (edn_rnd_i),
    .edn_urnd_o (edn_urnd_o),
    .edn_urnd_i (edn_urnd_i),
    .clk_otp_i (clk_otp_i_tb),
    .rst_otp_ni (rst_n),
    .otbn_otp_key_o (otbn_otp_key_o),
    .otbn_otp_key_i (otbn_otp_key_i),
    .keymgr_key_i (keymgr_key_i)
  );

  tb_clk_if clk_if (.clk(clk), .rst_n(rst_n));

  initial begin
    uvm_config_db#(virtual tb_clk_if)::set(null, "*", "clk_if", clk_if);
    run_test();
  end

  initial begin
    #1ms;
    `uvm_fatal("TB", "timeout -- simulation ran for 1ms with no test completion")
  end

endmodule
