// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// pinmux -- COMPILE-CHECK TESTBENCH   (generated by IP/scripts/gen_tb.py)
//
// A skeleton, not a verification environment. It proves the RTL and its
// dependencies elaborate and a UVM test can start and finish. Every input
// is tied to a constant; nothing is stimulated and nothing is checked.
// Building the environment is the exercise -- see ../README.md.

module tb;

  import uvm_pkg::*;
  import pinmux_test_pkg::*;
  import pinmux_pkg::*;
  import pinmux_reg_pkg::*;
  import prim_pad_wrapper_pkg::*;
  `include "uvm_macros.svh"

  // Clocks. The main bus clock is 100 MHz to match Earl Grey; slow
  // domains (aon / core / usb) get their own so the ratio is realistic.
  logic clk, rst_n;

  initial begin
    clk = 1'b0;
    forever #5ns clk = ~clk;
  end

  logic clk_aon_i_tb;
  initial begin
    clk_aon_i_tb = 1'b0;
    forever #20ns clk_aon_i_tb = ~clk_aon_i_tb;
  end

  initial begin
    rst_n = 1'b0;
    repeat (10) @(posedge clk);
    rst_n = 1'b1;
  end

  // Port declarations. Inputs are tied to constants -- never floating.
  prim_mubi_pkg::mubi4_t scanmode_i = '0;
  logic pin_wkup_req_o ;
  logic usb_wkup_req_o ;
  logic sleep_en_i = '0;
  logic strap_en_i = '0;
  logic strap_en_override_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_dft_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_hw_debug_clr_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_hw_debug_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_check_byp_en_i = '0;
  lc_ctrl_pkg::lc_tx_t lc_escalate_en_i = '0;
  lc_ctrl_pkg::lc_tx_t pinmux_hw_debug_en_o ;
  dft_strap_test_req_t dft_strap_test_o ;
  logic dft_hold_tap_sel_i = '0;
  jtag_pkg::jtag_req_t lc_jtag_o ;
  jtag_pkg::jtag_rsp_t lc_jtag_i = '0;
  jtag_pkg::jtag_req_t rv_jtag_o ;
  jtag_pkg::jtag_rsp_t rv_jtag_i = '0;
  jtag_pkg::jtag_req_t dft_jtag_o ;
  jtag_pkg::jtag_rsp_t dft_jtag_i = '0;
  logic usbdev_dppullup_en_i = '0;
  logic usbdev_dnpullup_en_i = '0;
  logic usb_dppullup_en_o ;
  logic usb_dnpullup_en_o ;
  logic usbdev_suspend_req_i = '0;
  logic usbdev_wake_ack_i = '0;
  logic usbdev_bus_not_idle_o ;
  logic usbdev_bus_reset_o ;
  logic usbdev_sense_lost_o ;
  logic usbdev_wake_detect_active_o ;
  tlul_pkg::tl_h2d_t tl_i = tlul_pkg::TL_H2D_DEFAULT;
  tlul_pkg::tl_d2h_t tl_o ;
  prim_alert_pkg::alert_rx_t [NumAlerts-1:0] alert_rx_i = '{default: prim_alert_pkg::ALERT_RX_DEFAULT};
  prim_alert_pkg::alert_tx_t [NumAlerts-1:0] alert_tx_o ;
  [NMioPeriphOut-1:0] periph_to_mio_i = '0;
  [NMioPeriphOut-1:0] periph_to_mio_oe_i = '0;
  logic [NMioPeriphIn-1:0] mio_to_periph_o ;
  [NDioPads-1:0] periph_to_dio_i = '0;
  [NDioPads-1:0] periph_to_dio_oe_i = '0;
  logic [NDioPads-1:0] dio_to_periph_o ;
  prim_pad_wrapper_pkg::pad_attr_t [NMioPads-1:0] mio_attr_o ;
  logic                            [NMioPads-1:0] mio_out_o ;
  logic                            [NMioPads-1:0] mio_oe_o ;
  [NMioPads-1:0] mio_in_i = '0;
  prim_pad_wrapper_pkg::pad_attr_t [NDioPads-1:0] dio_attr_o ;
  logic                            [NDioPads-1:0] dio_out_o ;
  logic                            [NDioPads-1:0] dio_oe_o ;
  [NDioPads-1:0] dio_in_i = '0;

  pinmux dut (
    .clk_i (clk),
    .rst_ni (rst_n),
    .rst_sys_ni (rst_n),
    .scanmode_i (scanmode_i),
    .clk_aon_i (clk_aon_i_tb),
    .rst_aon_ni (rst_n),
    .pin_wkup_req_o (pin_wkup_req_o),
    .usb_wkup_req_o (usb_wkup_req_o),
    .sleep_en_i (sleep_en_i),
    .strap_en_i (strap_en_i),
    .strap_en_override_i (strap_en_override_i),
    .lc_dft_en_i (lc_dft_en_i),
    .lc_hw_debug_clr_i (lc_hw_debug_clr_i),
    .lc_hw_debug_en_i (lc_hw_debug_en_i),
    .lc_check_byp_en_i (lc_check_byp_en_i),
    .lc_escalate_en_i (lc_escalate_en_i),
    .pinmux_hw_debug_en_o (pinmux_hw_debug_en_o),
    .dft_strap_test_o (dft_strap_test_o),
    .dft_hold_tap_sel_i (dft_hold_tap_sel_i),
    .lc_jtag_o (lc_jtag_o),
    .lc_jtag_i (lc_jtag_i),
    .rv_jtag_o (rv_jtag_o),
    .rv_jtag_i (rv_jtag_i),
    .dft_jtag_o (dft_jtag_o),
    .dft_jtag_i (dft_jtag_i),
    .usbdev_dppullup_en_i (usbdev_dppullup_en_i),
    .usbdev_dnpullup_en_i (usbdev_dnpullup_en_i),
    .usb_dppullup_en_o (usb_dppullup_en_o),
    .usb_dnpullup_en_o (usb_dnpullup_en_o),
    .usbdev_suspend_req_i (usbdev_suspend_req_i),
    .usbdev_wake_ack_i (usbdev_wake_ack_i),
    .usbdev_bus_not_idle_o (usbdev_bus_not_idle_o),
    .usbdev_bus_reset_o (usbdev_bus_reset_o),
    .usbdev_sense_lost_o (usbdev_sense_lost_o),
    .usbdev_wake_detect_active_o (usbdev_wake_detect_active_o),
    .tl_i (tl_i),
    .tl_o (tl_o),
    .alert_rx_i (alert_rx_i),
    .alert_tx_o (alert_tx_o),
    .periph_to_mio_i (periph_to_mio_i),
    .periph_to_mio_oe_i (periph_to_mio_oe_i),
    .mio_to_periph_o (mio_to_periph_o),
    .periph_to_dio_i (periph_to_dio_i),
    .periph_to_dio_oe_i (periph_to_dio_oe_i),
    .dio_to_periph_o (dio_to_periph_o),
    .mio_attr_o (mio_attr_o),
    .mio_out_o (mio_out_o),
    .mio_oe_o (mio_oe_o),
    .mio_in_i (mio_in_i),
    .dio_attr_o (dio_attr_o),
    .dio_out_o (dio_out_o),
    .dio_oe_o (dio_oe_o),
    .dio_in_i (dio_in_i)
  );

  tb_clk_if clk_if (.clk(clk), .rst_n(rst_n));

  initial begin
    uvm_config_db#(virtual tb_clk_if)::set(null, "*", "clk_if", clk_if);
    run_test();
  end

  initial begin
    #1ms;
    `uvm_fatal("TB", "timeout -- simulation ran for 1ms with no test completion")
  end

endmodule
